source 'https://rubygems.org'

gem 'rails', '4.0.3'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'inherited_resources'
gem 'haml-rails'
gem 'bootstrap-sass'
gem 'simple_form'
gem 'devise'
gem 'feedjira'
gem 'faraday'
gem 'faraday_middleware'
gem 'faraday_middleware-rss'
gem 'bootsy'

group :test, :development do
  gem 'spinach-rails'
  gem 'database_cleaner'
  gem 'rspec', '~> 2.13.0'
  gem 'email_spec'
  gem 'pry-nav'
end
